#!/usr/bin/env python3
"""Prepare a clean, uploadable Step 5/6 deliverable bundle.

This script copies evaluation artifacts from code/outputs_code4 and creates a compact
set of files in deliverables/step5_6 that specifically address:
- Step 5: evaluation + visualization of flagged anomalies
- Step 6: suitability discussion + trade-offs
"""

from __future__ import annotations

import csv
import json
import shutil
from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    src = repo_root / "code" / "outputs_code4"
    dst = repo_root / "deliverables" / "step5_6"
    fig_dst = dst / "figures"

    if not src.exists():
        raise FileNotFoundError(
            "Missing code/outputs_code4. Run `python code/evaluation_visualization_report.py` first to generate evaluation outputs."
        )

    dst.mkdir(parents=True, exist_ok=True)
    fig_dst.mkdir(parents=True, exist_ok=True)

    metrics_path = src / "metrics.json"
    analysis_path = src / "analysis.md"
    predictions_path = src / "predictions.csv"

    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))

    # 1) compact metrics table for upload/review
    compact_metrics = [
        ["rows_evaluated", metrics.get("n_rows", "")],
        ["predicted_anomalies", metrics.get("n_predicted_anomalies", "")],
        ["precision", metrics.get("precision", "")],
        ["recall", metrics.get("recall", "")],
        ["f1", metrics.get("f1", "")],
        ["false_positive_rate", metrics.get("false_positive_rate", "")],
    ]
    with (dst / "evaluation_metrics.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["metric", "value"])
        writer.writerows(compact_metrics)

    # 2) confusion matrix as a tiny clean csv
    cm = metrics.get("confusion_matrix", {})
    with (dst / "confusion_matrix.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["", "pred_normal", "pred_anomaly"])
        writer.writerow(["actual_normal", cm.get("tn", ""), cm.get("fp", "")])
        writer.writerow(["actual_anomaly", cm.get("fn", ""), cm.get("tp", "")])

    # 3) copy key visualizations (overlay plots + confusion matrix figure)
    selected_figures = sorted((src / "figures").glob("*_overlay.svg"))
    selected_figures += [src / "figures" / "confusion_matrix_weak_labels.svg"]
    for fig in selected_figures:
        if fig.exists():
            shutil.copy2(fig, fig_dst / fig.name)

    # 4) copy main predictions for traceability
    shutil.copy2(predictions_path, dst / "predictions.csv")

    # 5) step-specific documentation files
    step5_text = """# Step 5 — Evaluate and Visualize Detection Results

This folder contains a clean subset of evaluation outputs generated by `code/evaluation_visualization_report.py`.

## What is included
- `evaluation_metrics.csv`: precision/recall/F1/FPR and dataset size.
- `confusion_matrix.csv`: row-level weak-label confusion matrix values.
- `figures/*_overlay.svg`: original time-series overlaid with red anomaly flags.
- `figures/confusion_matrix_weak_labels.svg`: visual confusion matrix.
- `predictions.csv`: per-row anomaly predictions and scores.

## Interpretation guide
- In each overlay figure, the blue line is the original signal and red points are flagged anomalies.
- Weak labels come from folder origin (`normal` vs `anomalies`) and should be interpreted as approximate ground truth.
"""
    (dst / "step5_evaluation_and_visualization.md").write_text(step5_text, encoding="utf-8")

    step6_text = """# Step 6 — Suitability and Trade-Off Discussion

## Chosen approach
The project uses **Isolation Forest** for anomaly detection on multivariate telemetry.

## Why this approach is suitable
- Works well when detailed point-level labels are unavailable.
- Handles mixed process/resource metrics efficiently.
- Produces per-row outlier flags and scores for operational triage.

## Trade-offs observed
- Weak labels can overstate errors because anomaly files may still contain normal windows.
- A single threshold can lead to false positives if baseline behavior drifts.
- Isolation Forest is less interpretable than rule-based detectors without added diagnostics.

## Practical recommendation
Use model outputs as triage signals, then add threshold calibration and temporal smoothing to reduce alert noise.

---

For the full run-specific analysis narrative, see `analysis_full.md`.
"""
    (dst / "step6_suitability_tradeoffs.md").write_text(step6_text, encoding="utf-8")

    # include full analysis as a clean companion copy
    shutil.copy2(analysis_path, dst / "analysis_full.md")


if __name__ == "__main__":
    main()
